- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Unzip from APT
  apt:
    name: unzip
    state: present

- name: Download Packer from server
  unarchive:
    src: https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: Check Packer binary is avaiable
  wait_for:
    path: /usr/bin/packer
