- name: Update APT cache
  apt:
    update_cache: yes

- name: Add Docker GPG key to keyring
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository to sources.list
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: Install Docker dependencies
  apt:
    name: [ "aptitude", "apt-transport-https", "ca-certificates", "curl", "software-properties-common" ]
    update_cache: yes

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    update_cache: yes
